update
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>

diff --git a/.github/workflows/artifact-attestations.basic.yml b/.github/workflows/artifact-attestations.basic.yml
--- a/.github/workflows/artifact-attestations.basic.yml
+++ b/.github/workflows/artifact-attestations.basic.yml
@@ -51,7 +51,7 @@ jobs:
           echo "${result}" | jq '.[0].verificationResult.statement'
           opa_result="$(echo "${result}" | opa eval --stdin-input -f raw -d policy.rego "data.attestation.slsa1.allow == true")"
           echo "opa result: ${opa_result}"
-          [ "${opa_result}" != "true" ] && (echo "OPA policy should succeed!" && exit 1)
+          [ "${opa_result}" == "true" ] || (echo "OPA policy should succeed!" && exit 1)
 
   malicious:
     runs-on: ubuntu-latest
@@ -75,8 +75,5 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          result="$(gh attestation verify --repo ianlewis/gha-artifact-attestations-test --format json my-artifact)"
-          echo "${result}" | jq '.[0].verificationResult.statement'
-          opa_result="$(echo "${result}" | opa eval --stdin-input -f raw -d policy.rego "data.attestation.slsa1.allow == true")"
-          echo "opa result: ${opa_result}"
-          [ "${opa_result}" == "true" ] && echo "OPA policy should fail!" && exit 1
+          set +e
+          gh attestation verify --repo ianlewis/gha-artifact-attestations-test --format json my-artifact && (echo "gh attestation verify should fail" && exit 1)
