update
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>

diff --git a/.github/workflows/artifact-attestations.basic.yml b/.github/workflows/artifact-attestations.basic.yml
--- a/.github/workflows/artifact-attestations.basic.yml
+++ b/.github/workflows/artifact-attestations.basic.yml
@@ -48,12 +48,12 @@ jobs:
           GH_TOKEN: ${{ github.token }}
         run: |
           result="$(gh attestation verify --repo ianlewis/gha-artifact-attestations-test --format json my-artifact)"
-          echo "${result}"
+          echo "${result}" | jq '.[0].verificationResult.statement'
           opa_result="$(echo "${result}" | opa eval --stdin-input -f raw -d policy.rego "data.attestation.slsa1.allow == true")"
           if [ "${ACTIONS_RUNNER_DEBUG}" == "true" ]; then
             echo "opa result: ${opa_result}"
           fi
-          [ "${opa_result}" == "fail" ] || (echo "OPA policy should succeed!" && exit 1)
+          [ "${opa_result}" != "true" ] || (echo "OPA policy should succeed!" && exit 1)
 
   malicious:
     runs-on: ubuntu-latest
@@ -78,9 +78,9 @@ jobs:
           GH_TOKEN: ${{ github.token }}
         run: |
           result="$(gh attestation verify --repo ianlewis/gha-artifact-attestations-test --format json my-artifact)"
-          echo "${result}"
+          echo "${result}" | jq '.[0].verificationResult.statement'
           opa_result="$(echo "${result}" | opa eval --stdin-input -f raw -d policy.rego "data.attestation.slsa1.allow == true")"
           if [ "${ACTIONS_RUNNER_DEBUG}" == "true" ]; then
             echo "opa result: ${opa_result}"
           fi
-          [ "${opa_result}" == "fail" ] || (echo "OPA policy should fail!" && exit 1)
+          [ "${opa_result}" == "true" ] || (echo "OPA policy should fail!" && exit 1)
